version: '3.3'

services:
  app:
    image: desmond2_eval_container
    container_name: desmond2_eval_container
    build: .
    volumes:
      - desmond2-eval-volume:/tmp/q2_disc/
      - /local/desmond2-bicluster-eval/:/tmp/desmond2_bicluster_eval_results/
volumes:
  desmond2-eval-volume: