version: '3.3'

services:
  app:
    image: desmond2_eval_container_bc
    container_name: desmond2_eval_container_bc
    build: .
    volumes:
      - desmond2-eval-volume-bc:/tmp/q2_disc_bc/
      - /local/desmond2-bicluster-eval-bc/:/tmp/desmond2_bicluster_eval_results_bc/
volumes:
  desmond2-eval-volume-bc: