# action.yml
name: 'Tests'

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run tests
        uses: docker://freddsle/unpast:latest
        with:
          entrypoint: bash
          args: >
            -c "
            cd /github/workspace
            && pip install pytest --target /tmp
            && PYTHONPATH=/tmp python -m pytest unpast/tests -m 'not slow'
            && PYTHONPATH=/tmp python -m pytest unpast/tests --durations=0
            "
